### ISSUE TITLE
TypeError when decompiling

### ISSUE THREAD

**Issue by alanhamlett** [thenaterhood/basically-ti-basic#1]
``` python
Traceback (most recent call last):
  File "./basically-ti-basic-master/venv/bin/basically-ti-basic", line 9, in <module>
    load_entry_point('basically-ti-basic==0.1.2', 'console_scripts', 'basically-ti-basic')()
  File "build/bdist.macosx-10.11-intel/egg/basically_ti_basic/__main__.py", line 63, in main
  File "build/bdist.macosx-10.11-intel/egg/basically_ti_basic/__main__.py", line 21, in decompile_file
TypeError: unbound method decompile() must be called with PrgmCompiler instance as first argument (got TIPrgmFile instance instead)
```

When decompiling the 8xp from this zip file:
http://www.ticalc.org/pub/83plus/basic/games/simulation/vpet.zip

**Comment by thenaterhood** [comment]
Sorry, Github never notified me for this issue!

If you still have this issue and still have the same environment available, could you let me know what version of Python you're running? I'm not able to replicate this myself on Python 3.5.2, though it's certainly possible it has an issue on a different Python version.

**Comment by thenaterhood** [comment]
Shiny new release that should fix it. If you're interested in more info, take a look at the referenced pull.

Fixed in https://github.com/thenaterhood/basically-ti-basic/releases/tag/v0.1.3
